In [1]:
from collections import Counter
from sklearn.datasets import make_classification
from imblearn.ensemble import BalanceCascade
#import nslkdd41
import numpy as np
import classifier
#import unsw
import time
import cloud

#import cicids17

dt = cloud.read_data_sets()

X_train = dt.train.features
Y_train = dt.train.labels

X_test = dt.test.features
Y_test = dt.test.labels

Y_tr = np.argmax(Y_train, axis=1)
Y_te = np.argmax(Y_test, axis=1)
start = time.time()
sm = BalanceCascade(random_state=42)
X_res, Y_res = sm.fit_sample(X_train, Y_tr)
stop = time.time()
print ("thoi gian chay")
print (stop - start)


/usr/local/lib/python2.7/dist-packages/pandas/core/computation/__init__.py:18: UserWarning: The installed version of numexpr 2.4.3 is not supported in pandas and will be not be used
The minimum supported version is 2.4.6

  ver=ver, min_ver=_MIN_NUMEXPR_VERSION), UserWarning)


('total file: ', 2)
('total record: ', 4655)
('data shape: ', (4655, 25))
[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]
[[1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]]
thoi gian chay
0.564878940582


In [2]:
X_res = np.reshape(X_res, (len(X_res)*len(X_res[0]), len(X_res[0][0])))
Y_res = np.reshape(Y_res, (len(Y_res)*len(Y_res[0]), 1))
Y_test = np.reshape(Y_te, (len(Y_te), 1))


print ("-------------------------BALANCE CASCADA----------------------")
print ("SVM")
svm_roc_gan = classifier.svm(X_res, Y_res , X_test,Y_te)
print ("Decision tree")
dt_roc_gan = classifier.decisiontree(X_res, Y_res , X_test,Y_te)
print ("Random forest")
rf_roc_gan = classifier.randomforest(X_res, Y_res , X_test,Y_te)

24
90
68
(90, 68, 24)
(68, 24)
(90, 68)
(6120, 24)
(6120, 1)
-------------------------BALANCE CASCADA----------------------
SVM
SVM
                   pre       rec       spe        f1       geo       iba       sup

          0       1.00      1.00      1.00      1.00      1.00      1.00      1508
          1       1.00      1.00      1.00      1.00      1.00      1.00        29

avg / total       1.00      1.00      1.00      1.00      1.00      1.00      1537

[[1508    0]
 [   0   29]]
The geometric mean is 1.0
The auc is 1.0
The f1 is 1.0
Decision tree
Decision tree
                   pre       rec       spe        f1       geo       iba       sup

          0       1.00      1.00      1.00      1.00      1.00      1.00      1508
          1       1.00      1.00      1.00      1.00      1.00      1.00        29

avg / total       1.00      1.00      1.00      1.00      1.00      1.00      1537

[[1508    0]
 [   0   29]]
The geometric mean is 1.0
The auc is 1.0
The f1 is 1.0
Random

/usr/local/lib/python2.7/dist-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
classifier.py:248: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  clf.fit(X_tr, Y_tr)


             precision    recall  f1-score   support

          0       1.00      1.00      1.00      1508
          1       1.00      1.00      1.00        29

avg / total       1.00      1.00      1.00      1537

The geometric mean is 1.0
[[1508    0]
 [   0   29]]
The auc is 1.0
The f1 is 1.0
