In [1]:
from collections import Counter
from sklearn.datasets import make_classification
from imblearn.over_sampling import SMOTE 
#import nslkdd41
import numpy as np
import classifier
#import unsw
import time
#import cicids17
import cloud

dt = cloud.read_data_sets()

X_train = dt.train.features
Y_train = dt.train.labels

X_test = dt.test.features
Y_test = dt.test.labels

Y_tr = np.argmax(Y_train, axis=1)
Y_te = np.argmax(Y_test, axis=1)
start = time.time()
sm = SMOTE(random_state=42, kind = 'svm')
X_res, Y_res = sm.fit_sample(X_train, Y_tr)
stop = time.time()
print ("thoi gian chay")
print (stop - start)
print('original dataset shape {}'.format(Counter(Y_tr)))
print('Resampled dataset shape {}'.format(Counter(Y_res)))


/usr/local/lib/python2.7/dist-packages/pandas/core/computation/__init__.py:18: UserWarning: The installed version of numexpr 2.4.3 is not supported in pandas and will be not be used
The minimum supported version is 2.4.6

  ver=ver, min_ver=_MIN_NUMEXPR_VERSION), UserWarning)


('total file: ', 4)
('total record: ', 5137)
('data shape: ', (5137, 25))
[[0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]]
[[1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]]
thoi gian chay
0.351290941238
original dataset shape Counter({0: 3075, 1: 366})
Resampled dataset shape Counter({0: 3075, 1: 3075})


In [2]:
Y_res = np.reshape(Y_res, (len(Y_res), 1))

print ("-------------------------SMOTE-SVM---------------------")
print ("SVM")
svm_roc_gan = classifier.svm(X_res, Y_res , X_test,Y_te)
print ("Decision tree")
dt_roc_gan = classifier.decisiontree(X_res, Y_res , X_test,Y_te)
print ("Random forest")
rf_roc_gan = classifier.randomforest(X_res, Y_res , X_test,Y_te)

(6150, 1)
-------------------------SMOTE-SVM---------------------
SVM


/usr/local/lib/python2.7/dist-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVM
                   pre       rec       spe        f1       geo       iba       sup

          0       0.91      0.97      0.23      0.94      0.47      0.24      1517
          1       0.48      0.23      0.97      0.31      0.47      0.21       179

avg / total       0.87      0.89      0.31      0.88      0.47      0.24      1696

[[1473   44]
 [ 138   41]]
The geometric mean is 0.47160021661
The auc is 0.60002283248
The f1 is 0.892688679245
Decision tree
Decision tree
                   pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.99      0.97      0.99      0.98      0.95      1517
          1       0.89      0.97      0.99      0.93      0.98      0.95       179

avg / total       0.99      0.98      0.97      0.98      0.98      0.95      1696

[[1496   21]
 [   6  173]]
The geometric mean is 0.976269097345
The auc is 0.976318667762
The f1 is 0.984080188679
Random forest


classifier.py:248: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  clf.fit(X_tr, Y_tr)


             precision    recall  f1-score   support

          0       1.00      1.00      1.00      1517
          1       0.99      0.97      0.98       179

avg / total       1.00      1.00      1.00      1696

The geometric mean is 0.982449106703
[[1515    2]
 [   6  173]]
The auc is 0.982581027683
The f1 is 0.995283018868


In [3]:
from imblearn.combine import SMOTETomek

s1 = time.time()
sm = SMOTETomek()
X_resampled, y_resampled = sm.fit_sample(X_train, Y_tr)
s2 = time.time()
print ("smote tomek")
print (s2-s1)

smote tomek
0.232998847961


In [4]:
Y_res1 = np.reshape(y_resampled, (len(y_resampled), 1))
#Y_test1 = np.reshape(Y_te, (len(Y_te), 1))
print (Y_res1.shape)
print ("-------------------------SMOTE-TOMEK---------------------")
print ("SVM")
svm_roc_gan = classifier.svm(X_resampled, Y_res1 , X_test,Y_te)
print ("Decision tree")
dt_roc_gan = classifier.decisiontree(X_resampled, Y_res1 , X_test,Y_te)
print ("Random forest")
rf_roc_gan = classifier.randomforest(X_resampled, Y_res1 , X_test,Y_te)

(6142, 1)
-------------------------SMOTE-TOMEK---------------------
SVM
SVM
                   pre       rec       spe        f1       geo       iba       sup

          0       0.91      0.97      0.22      0.94      0.46      0.23      1517
          1       0.49      0.22      0.97      0.30      0.46      0.20       179

avg / total       0.87      0.89      0.30      0.87      0.46      0.22      1696

[[1477   40]
 [ 140   39]]
The geometric mean is 0.460578059073
The auc is 0.595754631863
The f1 is 0.893867924528
Decision tree
Decision tree
                   pre       rec       spe        f1       geo       iba       sup

          0       0.99      1.00      0.94      0.99      0.97      0.94      1517
          1       0.96      0.94      1.00      0.95      0.97      0.93       179

avg / total       0.99      0.99      0.94      0.99      0.97      0.94      1696

[[1510    7]
 [  11  168]]
The geometric mean is 0.966548850411
The auc is 0.966966557783
The f1 is 0.989386792

In [5]:
Y_res = np.reshape(Y_res, (len(Y_res), 1))
Y_test = np.reshape(Y_te, (len(Y_te), 1))
print (Y_res.shape)
print ("-------------------------SMOTE----------------------")
print ("SVM")
 svm_roc_gan = classifier.svm(X_res, Y_res , X_test,Y_te)
print ("Decision tree")
dt_roc_gan = classifier.decisiontree(X_res, Y_res , X_test,Y_te)
print ("Random forest")
 rf_roc_gan = classifier.randomforest(X_res, Y_res , X_test,Y_te)

IndentationError: unexpected indent (<ipython-input-5-a2b2d8d405ca>, line 6)